version: '3.9'

services:
  redis_db:
    extends:
      file: ./services/redis.yml
      service: redis_db
  backend:
    depends_on:
      - redis_db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.6.0
    volumes:
      - ./logs/:/app/logs/
    ports:
      - 4000:4000

  smart-contract-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    ports:
      - 8152:8050

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  stats:
    extends:
      file: ./services/stats-backend.yml
      service: stats
    ports:
      - 8153:8050

#
#  user-ops-indexer:
#    depends_on:
#      - backend
#    extends:
#      file: ./services/user-ops-indexer.yml
#      service: user-ops-indexer
