version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: <USERNAME>
      POSTGRES_PASSWORD: <PASSSWORD>
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ../postgres-data:/var/lib/postgresql/data